### ISSUE TITLE
Preparing the release of v2.5

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte.github.io#105]
uI recommend that we release v2.0 for now but some things need to be done before doing this. Below there's a list of what we've done so far and what we need to check.

# What we've done so far
## What @Discostu36  have done so far:
- [x] @Discostu36's commit [add cursor to pdv icon class ](https://github.com/babykarte/babykarte.github.io/commit/c47f8b982adbefc03da6668efaba9e85cbbe4351)
- [x] @Discostu36's commit [change font size](https://github.com/babykarte/babykarte.github.io/commit/de4466c1511aea8449c9e55bb7ecb816c205ca7e)
- [x] @Discostu36's commit [fix svg](https://github.com/babykarte/babykarte.github.io/commit/b8cd66982656e5f15fb788a78f95565500696be7)
- [x] @Discostu36 **merged a pull request** from @NicolasGrosjean 

## What @NicolasGrosjean have done so far:
- [x] @NicolasGrosjean's commit [Remove duplicate localisation](https://github.com/babykarte/babykarte.github.io/commit/7ddca4e60e1870d90d80213157c845d716a19f74) up to [Fix friendliness translation](https://github.com/babykarte/babykarte.github.io/commit/af8e38ccd5d41843676669e5da2d321e409ce3e7). See also [his pull request](https://github.com/babykarte/babykarte.github.io/pull/95).

## What I've done so far
- [x] Added support of [some of the values](https://github.com/babykarte/babykarte.github.io/issues/103#issuecomment-513582747) from the [Key:surface](http://wiki.osm.org/Key:surface)
- [x] Added support of [some of the values](https://github.com/babykarte/babykarte.github.io/issues/103#issuecomment-511984487) from the [Key:material](http://wiki.osm.org/Key:material)
- [x] Bugfixes in #97 
- [x] Switching from images to unicode where possible, see https://github.com/babykarte/babykarte.github.io/commit/84c8a54e5eeacc88f956d0f313af1fb932df842e and https://github.com/babykarte/babykarte.github.io/commit/b1c5f33b01e2ae1f551f6aec4fab787251f06b2a
- [x] Added support for multiple popups #103  #99 
- [x] Added the first subfilter #100 
- [x] Bugfix in issue #98, #96 
- [x] My commit [additions to README; #96 ; @NicolasGrosjean](https://github.com/babykarte/babykarte.github.io/commit/de934150db6d81c5bc955fc449806efc9912f912) because @NicolasGrosjean asked how to run a local copy of Babykarte. I assumed he was using linux for this because I always assume the use of linux.
- [x] My commit [activation of  french language, add to language ecosystem](https://github.com/babykarte/babykarte.github.io/commit/4133e42e5192b4bd007f02d237f7a3395d792fb1)

# What we need to do
- [x] Testing, if my commits for #103 are working.
- [x] Translating new strings into french. ( @NicolasGrosjean )
- [x] Improving english, french and german translation.

**Comment by Discostu36** [comment]
It's v3.0 🙂

**Comment by ValorNaram** [comment]
@Discostu36 We're ready to release!

**Comment by Discostu36** [comment]
I'll do some bug hunting and/or nitpicking in the next few days, then we can transfer to master.
